export const SET_NEW_MASJID_POSITION = 'SET_NEW_MASJID_POSITION';
export const TOGGLE_ADD_MASJID_FORM = 'TOGGLE_ADD_MASJID_FORM';
export const GET_All_MASJIDS = 'GET_All_MASJIDS';
export const MASJID_ERROR = 'MASJID_ERROR';
